#
# Module manifest for module 'Microsoft.Graph.Identity.Governance'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/8/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Identity.Governance.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '530fc574-049c-42cc-810e-8835853204b7'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.0.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Identity.Governance.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Identity.Governance.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Get-MgAgreement', 'Get-MgAgreementAcceptance', 
               'Get-MgAgreementAcceptanceCount', 'Get-MgAgreementFile', 
               'Get-MgAgreementFileCount', 'Get-MgAgreementFileLocalization', 
               'Get-MgAgreementFileLocalizationCount', 
               'Get-MgAgreementFileLocalizationVersion', 
               'Get-MgAgreementFileLocalizationVersionCount', 
               'Get-MgAgreementFileVersion', 'Get-MgAgreementFileVersionCount', 
               'Get-MgEntitlementManagementAccessPackage', 
               'Get-MgEntitlementManagementAccessPackageApplicablePolicyRequirement', 
               'Get-MgEntitlementManagementAccessPackageAssignmentApprovalCount', 
               'Get-MgEntitlementManagementAccessPackageAssignmentApprovalStage', 
               'Get-MgEntitlementManagementAccessPackageAssignmentApprovalStageCount', 
               'Get-MgEntitlementManagementAccessPackageAssignmentPolicy', 
               'Get-MgEntitlementManagementAccessPackageCatalog', 
               'Get-MgEntitlementManagementAccessPackageCount', 
               'Get-MgEntitlementManagementAccessPackageIncompatibleAccessPackage', 
               'Get-MgEntitlementManagementAccessPackageIncompatibleAccessPackageByRef', 
               'Get-MgEntitlementManagementAccessPackageIncompatibleGroup', 
               'Get-MgEntitlementManagementAccessPackageIncompatibleGroupByRef', 
               'Get-MgEntitlementManagementAccessPackageIncompatibleWith', 
               'Get-MgEntitlementManagementAssignment', 
               'Get-MgEntitlementManagementAssignmentAdditional', 
               'Get-MgEntitlementManagementAssignmentCount', 
               'Get-MgEntitlementManagementAssignmentPolicy', 
               'Get-MgEntitlementManagementAssignmentPolicyAccessPackage', 
               'Get-MgEntitlementManagementAssignmentPolicyCatalog', 
               'Get-MgEntitlementManagementAssignmentPolicyCount', 
               'Get-MgEntitlementManagementAssignmentPolicyQuestion', 
               'Get-MgEntitlementManagementAssignmentPolicyQuestionCount', 
               'Get-MgEntitlementManagementAssignmentRequest', 
               'Get-MgEntitlementManagementAssignmentRequestCount', 
               'Get-MgEntitlementManagementCatalog', 
               'Get-MgEntitlementManagementCatalogAccessPackageApplicablePolicyRequirement', 
               'Get-MgEntitlementManagementCatalogAccessPackageAssignmentPolicy', 
               'Get-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyAccessPackage', 
               'Get-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyCatalog', 
               'Get-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyCount', 
               'Get-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyQuestion', 
               'Get-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyQuestionCount', 
               'Get-MgEntitlementManagementCatalogAccessPackageCount', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleAccessPackage', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleAccessPackageByRef', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleAccessPackageCount', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleGroup', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleGroupByRef', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleGroupCount', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleWith', 
               'Get-MgEntitlementManagementCatalogAccessPackageIncompatibleWithCount', 
               'Get-MgEntitlementManagementCatalogCount', 
               'Get-MgEntitlementManagementConnectedOrganization', 
               'Get-MgEntitlementManagementConnectedOrganizationCount', 
               'Get-MgEntitlementManagementConnectedOrganizationExternalSponsor', 
               'Get-MgEntitlementManagementConnectedOrganizationExternalSponsorById', 
               'Get-MgEntitlementManagementConnectedOrganizationExternalSponsorByRef', 
               'Get-MgEntitlementManagementConnectedOrganizationExternalSponsorCount', 
               'Get-MgEntitlementManagementConnectedOrganizationExternalSponsorDelta', 
               'Get-MgEntitlementManagementConnectedOrganizationInternalSponsor', 
               'Get-MgEntitlementManagementConnectedOrganizationInternalSponsorById', 
               'Get-MgEntitlementManagementConnectedOrganizationInternalSponsorByRef', 
               'Get-MgEntitlementManagementConnectedOrganizationInternalSponsorCount', 
               'Get-MgEntitlementManagementConnectedOrganizationInternalSponsorDelta', 
               'Get-MgEntitlementManagementSetting', 
               'Get-MgIdentityGovernanceAccessReviewDefinition', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionCount', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstance', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewerCount', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceCount', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceDecisionCount', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceStageCount', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'Get-MgIdentityGovernanceAccessReviewDefinitionInstanceStageDecisionCount', 
               'Get-MgIdentityGovernanceAccessReviewHistoryDefinition', 
               'Get-MgIdentityGovernanceAccessReviewHistoryDefinitionCount', 
               'Get-MgIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'Get-MgIdentityGovernanceAccessReviewHistoryDefinitionInstanceCount', 
               'Get-MgIdentityGovernanceAppConsentRequest', 
               'Get-MgIdentityGovernanceAppConsentRequestCount', 
               'Get-MgIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'Get-MgIdentityGovernanceAppConsentRequestUserConsentRequestApproval', 
               'Get-MgIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStage', 
               'Get-MgIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStageCount', 
               'Get-MgIdentityGovernanceAppConsentRequestUserConsentRequestCount', 
               'Get-MgIdentityGovernanceTermsOfUseAgreement', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementAcceptance', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementAcceptanceCount', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementCount', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFile', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileCount', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileLocalization', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileLocalizationCount', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileLocalizationVersion', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileLocalizationVersionCount', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileVersion', 
               'Get-MgIdentityGovernanceTermsOfUseAgreementFileVersionCount', 
               'Get-MgRoleManagementDirectory', 
               'Get-MgRoleManagementDirectoryResourceNamespace', 
               'Get-MgRoleManagementDirectoryResourceNamespaceCount', 
               'Get-MgRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Get-MgRoleManagementDirectoryResourceNamespaceResourceActionCount', 
               'Get-MgRoleManagementDirectoryRoleAssignment', 
               'Get-MgRoleManagementDirectoryRoleAssignmentAppScope', 
               'Get-MgRoleManagementDirectoryRoleAssignmentCount', 
               'Get-MgRoleManagementDirectoryRoleAssignmentDirectoryScope', 
               'Get-MgRoleManagementDirectoryRoleAssignmentPrincipal', 
               'Get-MgRoleManagementDirectoryRoleAssignmentRoleDefinition', 
               'Get-MgRoleManagementDirectoryRoleAssignmentSchedule', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleActivatedUsing', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleCount', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleInstanceActivatedUsing', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleInstanceCount', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestActivatedUsing', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestAppScope', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestCount', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestDirectoryScope', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestPrincipal', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestRoleDefinition', 
               'Get-MgRoleManagementDirectoryRoleAssignmentScheduleRequestTargetSchedule', 
               'Get-MgRoleManagementDirectoryRoleDefinition', 
               'Get-MgRoleManagementDirectoryRoleDefinitionCount', 
               'Get-MgRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'Get-MgRoleManagementDirectoryRoleDefinitionInheritPermissionFromCount', 
               'Get-MgRoleManagementDirectoryRoleEligibilitySchedule', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleCount', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleInstanceCount', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequestAppScope', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequestCount', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequestDirectoryScope', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequestPrincipal', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequestRoleDefinition', 
               'Get-MgRoleManagementDirectoryRoleEligibilityScheduleRequestTargetSchedule', 
               'Get-MgRoleManagementEntitlementManagement', 
               'Get-MgRoleManagementEntitlementManagementResourceNamespace', 
               'Get-MgRoleManagementEntitlementManagementResourceNamespaceCount', 
               'Get-MgRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Get-MgRoleManagementEntitlementManagementResourceNamespaceResourceActionCount', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignment', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentAppScope', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentCount', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentDirectoryScope', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentPrincipal', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentRoleDefinition', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleActivatedUsing', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleCount', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleInstanceActivatedUsing', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleInstanceCount', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestActivatedUsing', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestAppScope', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestCount', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestDirectoryScope', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestPrincipal', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestRoleDefinition', 
               'Get-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequestTargetSchedule', 
               'Get-MgRoleManagementEntitlementManagementRoleDefinition', 
               'Get-MgRoleManagementEntitlementManagementRoleDefinitionCount', 
               'Get-MgRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'Get-MgRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFromCount', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleCount', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleInstanceCount', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequestAppScope', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequestCount', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequestDirectoryScope', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequestPrincipal', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequestRoleDefinition', 
               'Get-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequestTargetSchedule', 
               'Get-MgUserAgreementAcceptance', 
               'Get-MgUserAgreementAcceptanceCount', 
               'Invoke-MgAcceptIdentityGovernanceAccessReviewDefinitionInstanceRecommendation', 
               'Invoke-MgBatchIdentityGovernanceAccessReviewDefinitionInstanceRecordDecision', 
               'Invoke-MgFilterEntitlementManagementAccessPackageAssignmentApprovalByCurrentUser', 
               'Invoke-MgFilterEntitlementManagementAccessPackageByCurrentUser', 
               'Invoke-MgFilterEntitlementManagementAssignmentByCurrentUser', 
               'Invoke-MgFilterEntitlementManagementAssignmentRequestByCurrentUser', 
               'Invoke-MgFilterEntitlementManagementCatalogAccessPackageByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAccessReviewDefinitionByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAccessReviewDefinitionInstanceByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAccessReviewDefinitionInstanceDecisionByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAccessReviewDefinitionInstanceStageByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAccessReviewDefinitionInstanceStageDecisionByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAppConsentRequestByCurrentUser', 
               'Invoke-MgFilterIdentityGovernanceAppConsentRequestUserConsentRequestByCurrentUser', 
               'Invoke-MgFilterRoleManagementDirectoryRoleAssignmentScheduleByCurrentUser', 
               'Invoke-MgFilterRoleManagementDirectoryRoleAssignmentScheduleInstanceByCurrentUser', 
               'Invoke-MgFilterRoleManagementDirectoryRoleAssignmentScheduleRequestByCurrentUser', 
               'Invoke-MgFilterRoleManagementDirectoryRoleEligibilityScheduleByCurrentUser', 
               'Invoke-MgFilterRoleManagementDirectoryRoleEligibilityScheduleInstanceByCurrentUser', 
               'Invoke-MgFilterRoleManagementDirectoryRoleEligibilityScheduleRequestByCurrentUser', 
               'Invoke-MgFilterRoleManagementEntitlementManagementRoleAssignmentScheduleByCurrentUser', 
               'Invoke-MgFilterRoleManagementEntitlementManagementRoleAssignmentScheduleInstanceByCurrentUser', 
               'Invoke-MgFilterRoleManagementEntitlementManagementRoleAssignmentScheduleRequestByCurrentUser', 
               'Invoke-MgFilterRoleManagementEntitlementManagementRoleEligibilityScheduleByCurrentUser', 
               'Invoke-MgFilterRoleManagementEntitlementManagementRoleEligibilityScheduleInstanceByCurrentUser', 
               'Invoke-MgFilterRoleManagementEntitlementManagementRoleEligibilityScheduleRequestByCurrentUser', 
               'New-MgAgreement', 'New-MgAgreementAcceptance', 'New-MgAgreementFile', 
               'New-MgAgreementFileLocalization', 
               'New-MgAgreementFileLocalizationVersion', 
               'New-MgAgreementFileVersion', 
               'New-MgEntitlementManagementAccessPackage', 
               'New-MgEntitlementManagementAccessPackageAssignmentApprovalStage', 
               'New-MgEntitlementManagementAccessPackageAssignmentPolicy', 
               'New-MgEntitlementManagementAccessPackageIncompatibleAccessPackageByRef', 
               'New-MgEntitlementManagementAccessPackageIncompatibleGroupByRef', 
               'New-MgEntitlementManagementAssignment', 
               'New-MgEntitlementManagementAssignmentPolicy', 
               'New-MgEntitlementManagementAssignmentPolicyQuestion', 
               'New-MgEntitlementManagementAssignmentRequest', 
               'New-MgEntitlementManagementCatalog', 
               'New-MgEntitlementManagementCatalogAccessPackageAssignmentPolicy', 
               'New-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyQuestion', 
               'New-MgEntitlementManagementCatalogAccessPackageIncompatibleAccessPackageByRef', 
               'New-MgEntitlementManagementCatalogAccessPackageIncompatibleGroupByRef', 
               'New-MgEntitlementManagementConnectedOrganization', 
               'New-MgEntitlementManagementConnectedOrganizationExternalSponsorByRef', 
               'New-MgEntitlementManagementConnectedOrganizationInternalSponsorByRef', 
               'New-MgIdentityGovernanceAccessReviewDefinition', 
               'New-MgIdentityGovernanceAccessReviewDefinitionInstance', 
               'New-MgIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'New-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'New-MgIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'New-MgIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'New-MgIdentityGovernanceAccessReviewHistoryDefinition', 
               'New-MgIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'New-MgIdentityGovernanceAccessReviewHistoryDefinitionInstanceDownloadUri', 
               'New-MgIdentityGovernanceAppConsentRequest', 
               'New-MgIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'New-MgIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStage', 
               'New-MgIdentityGovernanceTermsOfUseAgreement', 
               'New-MgIdentityGovernanceTermsOfUseAgreementAcceptance', 
               'New-MgIdentityGovernanceTermsOfUseAgreementFile', 
               'New-MgIdentityGovernanceTermsOfUseAgreementFileLocalization', 
               'New-MgIdentityGovernanceTermsOfUseAgreementFileLocalizationVersion', 
               'New-MgIdentityGovernanceTermsOfUseAgreementFileVersion', 
               'New-MgRoleManagementDirectoryResourceNamespace', 
               'New-MgRoleManagementDirectoryResourceNamespaceResourceAction', 
               'New-MgRoleManagementDirectoryRoleAssignment', 
               'New-MgRoleManagementDirectoryRoleAssignmentSchedule', 
               'New-MgRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'New-MgRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'New-MgRoleManagementDirectoryRoleDefinition', 
               'New-MgRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'New-MgRoleManagementDirectoryRoleEligibilitySchedule', 
               'New-MgRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'New-MgRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'New-MgRoleManagementEntitlementManagementResourceNamespace', 
               'New-MgRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'New-MgRoleManagementEntitlementManagementRoleAssignment', 
               'New-MgRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'New-MgRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'New-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'New-MgRoleManagementEntitlementManagementRoleDefinition', 
               'New-MgRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'New-MgRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'New-MgRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'New-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Remove-MgAgreement', 'Remove-MgAgreementAcceptance', 
               'Remove-MgAgreementFile', 'Remove-MgAgreementFileLocalization', 
               'Remove-MgAgreementFileLocalizationVersion', 
               'Remove-MgAgreementFileVersion', 
               'Remove-MgEntitlementManagementAccessPackage', 
               'Remove-MgEntitlementManagementAccessPackageAssignmentApproval', 
               'Remove-MgEntitlementManagementAccessPackageAssignmentApprovalStage', 
               'Remove-MgEntitlementManagementAccessPackageAssignmentPolicy', 
               'Remove-MgEntitlementManagementAccessPackageIncompatibleAccessPackageByRef', 
               'Remove-MgEntitlementManagementAccessPackageIncompatibleGroupByRef', 
               'Remove-MgEntitlementManagementAssignment', 
               'Remove-MgEntitlementManagementAssignmentPolicy', 
               'Remove-MgEntitlementManagementAssignmentPolicyQuestion', 
               'Remove-MgEntitlementManagementAssignmentRequest', 
               'Remove-MgEntitlementManagementCatalog', 
               'Remove-MgEntitlementManagementCatalogAccessPackageAssignmentPolicy', 
               'Remove-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyQuestion', 
               'Remove-MgEntitlementManagementCatalogAccessPackageIncompatibleAccessPackageByRef', 
               'Remove-MgEntitlementManagementCatalogAccessPackageIncompatibleGroupByRef', 
               'Remove-MgEntitlementManagementConnectedOrganization', 
               'Remove-MgEntitlementManagementConnectedOrganizationExternalSponsorByRef', 
               'Remove-MgEntitlementManagementConnectedOrganizationInternalSponsorByRef', 
               'Remove-MgIdentityGovernanceAccessReviewDefinition', 
               'Remove-MgIdentityGovernanceAccessReviewDefinitionInstance', 
               'Remove-MgIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'Remove-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Remove-MgIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Remove-MgIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'Remove-MgIdentityGovernanceAccessReviewHistoryDefinition', 
               'Remove-MgIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'Remove-MgIdentityGovernanceAppConsentRequest', 
               'Remove-MgIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'Remove-MgIdentityGovernanceAppConsentRequestUserConsentRequestApproval', 
               'Remove-MgIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStage', 
               'Remove-MgIdentityGovernanceTermsOfUseAgreement', 
               'Remove-MgIdentityGovernanceTermsOfUseAgreementAcceptance', 
               'Remove-MgIdentityGovernanceTermsOfUseAgreementFile', 
               'Remove-MgIdentityGovernanceTermsOfUseAgreementFileLocalization', 
               'Remove-MgIdentityGovernanceTermsOfUseAgreementFileLocalizationVersion', 
               'Remove-MgIdentityGovernanceTermsOfUseAgreementFileVersion', 
               'Remove-MgRoleManagementDirectory', 
               'Remove-MgRoleManagementDirectoryResourceNamespace', 
               'Remove-MgRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Remove-MgRoleManagementDirectoryRoleAssignment', 
               'Remove-MgRoleManagementDirectoryRoleAssignmentAppScope', 
               'Remove-MgRoleManagementDirectoryRoleAssignmentSchedule', 
               'Remove-MgRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'Remove-MgRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Remove-MgRoleManagementDirectoryRoleDefinition', 
               'Remove-MgRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'Remove-MgRoleManagementDirectoryRoleEligibilitySchedule', 
               'Remove-MgRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'Remove-MgRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Remove-MgRoleManagementEntitlementManagement', 
               'Remove-MgRoleManagementEntitlementManagementResourceNamespace', 
               'Remove-MgRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Remove-MgRoleManagementEntitlementManagementRoleAssignment', 
               'Remove-MgRoleManagementEntitlementManagementRoleAssignmentAppScope', 
               'Remove-MgRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'Remove-MgRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'Remove-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Remove-MgRoleManagementEntitlementManagementRoleDefinition', 
               'Remove-MgRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'Remove-MgRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'Remove-MgRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'Remove-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Reset-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Send-MgIdentityGovernanceAccessReviewDefinitionInstanceReminder', 
               'Set-MgEntitlementManagementAssignmentPolicy', 
               'Stop-MgEntitlementManagementAssignmentRequest', 
               'Stop-MgIdentityGovernanceAccessReviewDefinition', 
               'Stop-MgIdentityGovernanceAccessReviewDefinitionInstance', 
               'Stop-MgIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Stop-MgRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Stop-MgRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Stop-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Stop-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequest', 
               'Test-MgEntitlementManagementConnectedOrganizationExternalSponsorProperty', 
               'Test-MgEntitlementManagementConnectedOrganizationInternalSponsorProperty', 
               'Update-MgAgreement', 'Update-MgAgreementAcceptance', 
               'Update-MgAgreementFile', 'Update-MgAgreementFileLocalization', 
               'Update-MgAgreementFileLocalizationVersion', 
               'Update-MgAgreementFileVersion', 
               'Update-MgEntitlementManagementAccessPackage', 
               'Update-MgEntitlementManagementAccessPackageAssignmentApproval', 
               'Update-MgEntitlementManagementAccessPackageAssignmentApprovalStage', 
               'Update-MgEntitlementManagementAccessPackageAssignmentPolicy', 
               'Update-MgEntitlementManagementAssignment', 
               'Update-MgEntitlementManagementAssignmentPolicyQuestion', 
               'Update-MgEntitlementManagementAssignmentRequest', 
               'Update-MgEntitlementManagementCatalog', 
               'Update-MgEntitlementManagementCatalogAccessPackageAssignmentPolicy', 
               'Update-MgEntitlementManagementCatalogAccessPackageAssignmentPolicyQuestion', 
               'Update-MgEntitlementManagementConnectedOrganization', 
               'Update-MgEntitlementManagementSetting', 
               'Update-MgIdentityGovernanceAccessReviewDefinition', 
               'Update-MgIdentityGovernanceAccessReviewDefinitionInstance', 
               'Update-MgIdentityGovernanceAccessReviewDefinitionInstanceContactedReviewer', 
               'Update-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision', 
               'Update-MgIdentityGovernanceAccessReviewDefinitionInstanceStage', 
               'Update-MgIdentityGovernanceAccessReviewDefinitionInstanceStageDecision', 
               'Update-MgIdentityGovernanceAccessReviewHistoryDefinition', 
               'Update-MgIdentityGovernanceAccessReviewHistoryDefinitionInstance', 
               'Update-MgIdentityGovernanceAppConsentRequest', 
               'Update-MgIdentityGovernanceAppConsentRequestUserConsentRequest', 
               'Update-MgIdentityGovernanceAppConsentRequestUserConsentRequestApproval', 
               'Update-MgIdentityGovernanceAppConsentRequestUserConsentRequestApprovalStage', 
               'Update-MgIdentityGovernanceTermsOfUseAgreement', 
               'Update-MgIdentityGovernanceTermsOfUseAgreementAcceptance', 
               'Update-MgIdentityGovernanceTermsOfUseAgreementFile', 
               'Update-MgIdentityGovernanceTermsOfUseAgreementFileLocalization', 
               'Update-MgIdentityGovernanceTermsOfUseAgreementFileLocalizationVersion', 
               'Update-MgIdentityGovernanceTermsOfUseAgreementFileVersion', 
               'Update-MgRoleManagementDirectory', 
               'Update-MgRoleManagementDirectoryResourceNamespace', 
               'Update-MgRoleManagementDirectoryResourceNamespaceResourceAction', 
               'Update-MgRoleManagementDirectoryRoleAssignment', 
               'Update-MgRoleManagementDirectoryRoleAssignmentAppScope', 
               'Update-MgRoleManagementDirectoryRoleAssignmentSchedule', 
               'Update-MgRoleManagementDirectoryRoleAssignmentScheduleInstance', 
               'Update-MgRoleManagementDirectoryRoleAssignmentScheduleRequest', 
               'Update-MgRoleManagementDirectoryRoleDefinition', 
               'Update-MgRoleManagementDirectoryRoleDefinitionInheritPermissionFrom', 
               'Update-MgRoleManagementDirectoryRoleEligibilitySchedule', 
               'Update-MgRoleManagementDirectoryRoleEligibilityScheduleInstance', 
               'Update-MgRoleManagementDirectoryRoleEligibilityScheduleRequest', 
               'Update-MgRoleManagementEntitlementManagement', 
               'Update-MgRoleManagementEntitlementManagementResourceNamespace', 
               'Update-MgRoleManagementEntitlementManagementResourceNamespaceResourceAction', 
               'Update-MgRoleManagementEntitlementManagementRoleAssignment', 
               'Update-MgRoleManagementEntitlementManagementRoleAssignmentAppScope', 
               'Update-MgRoleManagementEntitlementManagementRoleAssignmentSchedule', 
               'Update-MgRoleManagementEntitlementManagementRoleAssignmentScheduleInstance', 
               'Update-MgRoleManagementEntitlementManagementRoleAssignmentScheduleRequest', 
               'Update-MgRoleManagementEntitlementManagementRoleDefinition', 
               'Update-MgRoleManagementEntitlementManagementRoleDefinitionInheritPermissionFrom', 
               'Update-MgRoleManagementEntitlementManagementRoleEligibilitySchedule', 
               'Update-MgRoleManagementEntitlementManagementRoleEligibilityScheduleInstance', 
               'Update-MgRoleManagementEntitlementManagementRoleEligibilityScheduleRequest'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        Prerelease = 'preview10'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

