#
# Module manifest for module 'Microsoft.Graph.Beta.Security'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/8/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.Security.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd924e36b-d6ef-4536-bfdd-968457edd058'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.0.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.Security.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.Security.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgBetaSecurityCaseEdiscoveryCaseCustodianHold', 
               'Add-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSourceHold', 
               'Add-MgBetaSecurityCaseEdiscoveryCaseReviewSetQueryTag', 
               'Add-MgBetaSecurityCaseEdiscoveryCaseReviewSetToReviewSet', 
               'Clear-MgBetaSecurityCaseEdiscoveryCaseSearchData', 
               'Close-MgBetaSecurityCaseEdiscoveryCase', 
               'Export-MgBetaSecurityCaseEdiscoveryCaseReviewSet', 
               'Export-MgBetaSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Get-MgBetaSecurityAction', 'Get-MgBetaSecurityActionCount', 
               'Get-MgBetaSecurityAlert', 'Get-MgBetaSecurityAlertCount', 
               'Get-MgBetaSecurityAlertV2', 'Get-MgBetaSecurityAlertV2Count', 
               'Get-MgBetaSecurityAttackSimulation', 
               'Get-MgBetaSecurityAttackSimulationAutomation', 
               'Get-MgBetaSecurityAttackSimulationAutomationCount', 
               'Get-MgBetaSecurityAttackSimulationAutomationRun', 
               'Get-MgBetaSecurityAttackSimulationAutomationRunCount', 
               'Get-MgBetaSecurityAttackSimulationCount', 
               'Get-MgBetaSecurityAttackSimulationOperation', 
               'Get-MgBetaSecurityAttackSimulationOperationCount', 
               'Get-MgBetaSecurityAttackSimulationPayload', 
               'Get-MgBetaSecurityAttackSimulationPayloadCount', 
               'Get-MgBetaSecurityCase', 'Get-MgBetaSecurityCaseEdiscoveryCase', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodian', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianLastIndexOperation', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianSiteSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianSiteSourceSite', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSourceGroup', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseCustodianUserSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHold', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHoldCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHoldSiteSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHoldSiteSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHoldSiteSourceSite', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHoldUserSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseLegalHoldUserSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSourceLastIndexOperation', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseOperation', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseOperationCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSet', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFile', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileContent', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileCustodian', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileExtractedTextContent', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileTag', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileTagCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseReviewSetQueryCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearch', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchAdditionalSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchAddToReviewSetOperation', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchCustodianSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchCustodianSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchLastEstimateStatisticsOperation', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchNoncustodialSource', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSearchNoncustodialSourceCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseSetting', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseTag', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseTagChildTag', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseTagChildTagCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseTagCount', 
               'Get-MgBetaSecurityCaseEdiscoveryCaseTagParent', 
               'Get-MgBetaSecurityCloudAppSecurityProfile', 
               'Get-MgBetaSecurityCloudAppSecurityProfileCount', 
               'Get-MgBetaSecurityDomainSecurityProfile', 
               'Get-MgBetaSecurityDomainSecurityProfileCount', 
               'Get-MgBetaSecurityFileSecurityProfile', 
               'Get-MgBetaSecurityFileSecurityProfileCount', 
               'Get-MgBetaSecurityHostSecurityProfile', 
               'Get-MgBetaSecurityHostSecurityProfileCount', 
               'Get-MgBetaSecurityIncident', 'Get-MgBetaSecurityIncidentAlert', 
               'Get-MgBetaSecurityIncidentAlertCount', 
               'Get-MgBetaSecurityIncidentCount', 
               'Get-MgBetaSecurityInformationProtection', 
               'Get-MgBetaSecurityInformationProtectionLabelPolicySetting', 
               'Get-MgBetaSecurityInformationProtectionSensitivityLabel', 
               'Get-MgBetaSecurityInformationProtectionSensitivityLabelCount', 
               'Get-MgBetaSecurityInformationProtectionSensitivityLabelParent', 
               'Get-MgBetaSecurityIPSecurityProfile', 
               'Get-MgBetaSecurityIPSecurityProfileCount', 
               'Get-MgBetaSecurityLabel', 
               'Get-MgBetaSecurityLabelRetentionEventType', 
               'Get-MgBetaSecurityLabelRetentionLabel', 
               'Get-MgBetaSecurityLabelRetentionLabelCount', 
               'Get-MgBetaSecurityLabelRetentionLabelDispositionReviewStage', 
               'Get-MgBetaSecurityLabelRetentionLabelDispositionReviewStageCount', 
               'Get-MgBetaSecurityProviderTenantSetting', 
               'Get-MgBetaSecurityProviderTenantSettingCount', 
               'Get-MgBetaSecuritySecureScore', 
               'Get-MgBetaSecuritySecureScoreControlProfile', 
               'Get-MgBetaSecuritySecureScoreControlProfileCount', 
               'Get-MgBetaSecuritySecureScoreCount', 
               'Get-MgBetaSecuritySubjectRightsRequest', 
               'Get-MgBetaSecuritySubjectRightsRequestApprover', 
               'Get-MgBetaSecuritySubjectRightsRequestApproverCount', 
               'Get-MgBetaSecuritySubjectRightsRequestApproverMailboxSetting', 
               'Get-MgBetaSecuritySubjectRightsRequestCollaborator', 
               'Get-MgBetaSecuritySubjectRightsRequestCollaboratorCount', 
               'Get-MgBetaSecuritySubjectRightsRequestCollaboratorMailboxSetting', 
               'Get-MgBetaSecuritySubjectRightsRequestCount', 
               'Get-MgBetaSecuritySubjectRightsRequestFinalAttachment', 
               'Get-MgBetaSecuritySubjectRightsRequestFinalReport', 
               'Get-MgBetaSecuritySubjectRightsRequestNote', 
               'Get-MgBetaSecuritySubjectRightsRequestNoteCount', 
               'Get-MgBetaSecuritySubjectRightsRequestTeam', 
               'Get-MgBetaSecurityThreatIntelligence', 
               'Get-MgBetaSecurityThreatIntelligenceArticle', 
               'Get-MgBetaSecurityThreatIntelligenceArticleCount', 
               'Get-MgBetaSecurityThreatIntelligenceArticleIndicator', 
               'Get-MgBetaSecurityThreatIntelligenceArticleIndicatorCount', 
               'Get-MgBetaSecurityThreatIntelligenceHost', 
               'Get-MgBetaSecurityThreatIntelligenceHostComponent', 
               'Get-MgBetaSecurityThreatIntelligenceHostComponentCount', 
               'Get-MgBetaSecurityThreatIntelligenceHostComponentHost', 
               'Get-MgBetaSecurityThreatIntelligenceHostCookie', 
               'Get-MgBetaSecurityThreatIntelligenceHostCookieCount', 
               'Get-MgBetaSecurityThreatIntelligenceHostCookieHost', 
               'Get-MgBetaSecurityThreatIntelligenceHostCount', 
               'Get-MgBetaSecurityThreatIntelligenceHostPassiveDns', 
               'Get-MgBetaSecurityThreatIntelligenceHostPassiveDnsCount', 
               'Get-MgBetaSecurityThreatIntelligenceHostPassiveDnsReverse', 
               'Get-MgBetaSecurityThreatIntelligenceHostPassiveDnsReverseCount', 
               'Get-MgBetaSecurityThreatIntelligenceHostReputation', 
               'Get-MgBetaSecurityThreatIntelligenceHostTracker', 
               'Get-MgBetaSecurityThreatIntelligenceHostTrackerCount', 
               'Get-MgBetaSecurityThreatIntelligenceHostTrackerHost', 
               'Get-MgBetaSecurityThreatIntelligenceIntelProfile', 
               'Get-MgBetaSecurityThreatIntelligenceIntelProfileCount', 
               'Get-MgBetaSecurityThreatIntelligenceIntelProfileIndicator', 
               'Get-MgBetaSecurityThreatIntelligenceIntelProfileIndicatorCount', 
               'Get-MgBetaSecurityThreatIntelligencePassiveDnsRecord', 
               'Get-MgBetaSecurityThreatIntelligencePassiveDnsRecordArtifact', 
               'Get-MgBetaSecurityThreatIntelligencePassiveDnsRecordCount', 
               'Get-MgBetaSecurityThreatIntelligencePassiveDnsRecordParentHost', 
               'Get-MgBetaSecurityThreatIntelligenceProfileIndicator', 
               'Get-MgBetaSecurityThreatIntelligenceProfileIndicatorCount', 
               'Get-MgBetaSecurityThreatIntelligenceVulnerability', 
               'Get-MgBetaSecurityThreatIntelligenceVulnerabilityArticle', 
               'Get-MgBetaSecurityThreatIntelligenceVulnerabilityArticleCount', 
               'Get-MgBetaSecurityThreatIntelligenceVulnerabilityComponent', 
               'Get-MgBetaSecurityThreatIntelligenceVulnerabilityComponentCount', 
               'Get-MgBetaSecurityThreatIntelligenceVulnerabilityCount', 
               'Get-MgBetaSecurityThreatSubmission', 
               'Get-MgBetaSecurityThreatSubmissionEmailThreat', 
               'Get-MgBetaSecurityThreatSubmissionEmailThreatCount', 
               'Get-MgBetaSecurityThreatSubmissionEmailThreatSubmissionPolicy', 
               'Get-MgBetaSecurityThreatSubmissionEmailThreatSubmissionPolicyCount', 
               'Get-MgBetaSecurityThreatSubmissionFileThreat', 
               'Get-MgBetaSecurityThreatSubmissionFileThreatCount', 
               'Get-MgBetaSecurityThreatSubmissionUrlThreat', 
               'Get-MgBetaSecurityThreatSubmissionUrlThreatCount', 
               'Get-MgBetaSecurityTiIndicator', 
               'Get-MgBetaSecurityTiIndicatorCount', 'Get-MgBetaSecurityTrigger', 
               'Get-MgBetaSecurityTriggerRetentionEvent', 
               'Get-MgBetaSecurityTriggerRetentionEventCount', 
               'Get-MgBetaSecurityTriggerRetentionEventType', 
               'Get-MgBetaSecurityTriggerType', 
               'Get-MgBetaSecurityTriggerTypeRetentionEventType', 
               'Get-MgBetaSecurityTriggerTypeRetentionEventTypeCount', 
               'Get-MgBetaSecurityUserSecurityProfile', 
               'Get-MgBetaSecurityUserSecurityProfileCount', 
               'Initialize-MgBetaSecurityCaseEdiscoveryCaseCustodian', 
               'Invoke-MgBetaAsSecurityCaseEdiscoveryCaseTagHierarchy', 
               'Invoke-MgBetaEstimatestatisticSecurityCaseEdiscoveryCaseSearch', 
               'Invoke-MgBetaExtractSecurityInformationProtectionSensitivityLabelContentLabel', 
               'Invoke-MgBetaReopenSecurityCaseEdiscoveryCase', 
               'New-MgBetaSecurityAction', 'New-MgBetaSecurityAlert', 
               'New-MgBetaSecurityAlertV2', 'New-MgBetaSecurityAttackSimulation', 
               'New-MgBetaSecurityAttackSimulationAutomation', 
               'New-MgBetaSecurityAttackSimulationAutomationRun', 
               'New-MgBetaSecurityAttackSimulationOperation', 
               'New-MgBetaSecurityAttackSimulationPayload', 
               'New-MgBetaSecurityCaseEdiscoveryCase', 
               'New-MgBetaSecurityCaseEdiscoveryCaseCustodian', 
               'New-MgBetaSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseLegalHold', 
               'New-MgBetaSecurityCaseEdiscoveryCaseLegalHoldSiteSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseLegalHoldUserSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseOperation', 
               'New-MgBetaSecurityCaseEdiscoveryCaseReviewSet', 
               'New-MgBetaSecurityCaseEdiscoveryCaseReviewSetFile', 
               'New-MgBetaSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'New-MgBetaSecurityCaseEdiscoveryCaseSearch', 
               'New-MgBetaSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'New-MgBetaSecurityCaseEdiscoveryCaseTag', 
               'New-MgBetaSecurityCloudAppSecurityProfile', 
               'New-MgBetaSecurityDomainSecurityProfile', 
               'New-MgBetaSecurityFileSecurityProfile', 
               'New-MgBetaSecurityHostSecurityProfile', 
               'New-MgBetaSecurityIncident', 
               'New-MgBetaSecurityInformationProtectionSensitivityLabel', 
               'New-MgBetaSecurityIPSecurityProfile', 
               'New-MgBetaSecurityLabelRetentionLabel', 
               'New-MgBetaSecurityLabelRetentionLabelDispositionReviewStage', 
               'New-MgBetaSecurityProviderTenantSetting', 
               'New-MgBetaSecuritySecureScore', 
               'New-MgBetaSecuritySecureScoreControlProfile', 
               'New-MgBetaSecuritySubjectRightsRequest', 
               'New-MgBetaSecuritySubjectRightsRequestNote', 
               'New-MgBetaSecurityThreatIntelligenceArticle', 
               'New-MgBetaSecurityThreatIntelligenceArticleIndicator', 
               'New-MgBetaSecurityThreatIntelligenceHost', 
               'New-MgBetaSecurityThreatIntelligenceHostComponent', 
               'New-MgBetaSecurityThreatIntelligenceHostCookie', 
               'New-MgBetaSecurityThreatIntelligenceHostTracker', 
               'New-MgBetaSecurityThreatIntelligenceIntelProfile', 
               'New-MgBetaSecurityThreatIntelligencePassiveDnsRecord', 
               'New-MgBetaSecurityThreatIntelligenceProfileIndicator', 
               'New-MgBetaSecurityThreatIntelligenceVulnerability', 
               'New-MgBetaSecurityThreatIntelligenceVulnerabilityComponent', 
               'New-MgBetaSecurityThreatSubmissionEmailThreat', 
               'New-MgBetaSecurityThreatSubmissionEmailThreatSubmissionPolicy', 
               'New-MgBetaSecurityThreatSubmissionFileThreat', 
               'New-MgBetaSecurityThreatSubmissionUrlThreat', 
               'New-MgBetaSecurityTiIndicator', 
               'New-MgBetaSecurityTriggerRetentionEvent', 
               'New-MgBetaSecurityTriggerTypeRetentionEventType', 
               'New-MgBetaSecurityUserSecurityProfile', 
               'Publish-MgBetaSecurityCaseEdiscoveryCaseCustodian', 
               'Publish-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Remove-MgBetaSecurityAction', 'Remove-MgBetaSecurityAlertV2', 
               'Remove-MgBetaSecurityAttackSimulation', 
               'Remove-MgBetaSecurityAttackSimulationAutomation', 
               'Remove-MgBetaSecurityAttackSimulationAutomationRun', 
               'Remove-MgBetaSecurityAttackSimulationOperation', 
               'Remove-MgBetaSecurityAttackSimulationPayload', 
               'Remove-MgBetaSecurityCase', 
               'Remove-MgBetaSecurityCaseEdiscoveryCase', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseCustodian', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseCustodianHold', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseLegalHold', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseLegalHoldSiteSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseLegalHoldUserSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSourceHold', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseOperation', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseReviewSet', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseReviewSetFile', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseSearch', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseSetting', 
               'Remove-MgBetaSecurityCaseEdiscoveryCaseTag', 
               'Remove-MgBetaSecurityCloudAppSecurityProfile', 
               'Remove-MgBetaSecurityDomainSecurityProfile', 
               'Remove-MgBetaSecurityFileSecurityProfile', 
               'Remove-MgBetaSecurityHostSecurityProfile', 
               'Remove-MgBetaSecurityIncident', 
               'Remove-MgBetaSecurityInformationProtection', 
               'Remove-MgBetaSecurityInformationProtectionLabelPolicySetting', 
               'Remove-MgBetaSecurityInformationProtectionSensitivityLabel', 
               'Remove-MgBetaSecurityInformationProtectionSensitivityLabelParent', 
               'Remove-MgBetaSecurityIPSecurityProfile', 
               'Remove-MgBetaSecurityLabel', 
               'Remove-MgBetaSecurityLabelRetentionLabel', 
               'Remove-MgBetaSecurityLabelRetentionLabelDispositionReviewStage', 
               'Remove-MgBetaSecurityProviderTenantSetting', 
               'Remove-MgBetaSecuritySecureScore', 
               'Remove-MgBetaSecuritySecureScoreControlProfile', 
               'Remove-MgBetaSecuritySubjectRightsRequest', 
               'Remove-MgBetaSecuritySubjectRightsRequestNote', 
               'Remove-MgBetaSecurityThreatIntelligence', 
               'Remove-MgBetaSecurityThreatIntelligenceArticle', 
               'Remove-MgBetaSecurityThreatIntelligenceArticleIndicator', 
               'Remove-MgBetaSecurityThreatIntelligenceHost', 
               'Remove-MgBetaSecurityThreatIntelligenceHostComponent', 
               'Remove-MgBetaSecurityThreatIntelligenceHostCookie', 
               'Remove-MgBetaSecurityThreatIntelligenceHostReputation', 
               'Remove-MgBetaSecurityThreatIntelligenceHostTracker', 
               'Remove-MgBetaSecurityThreatIntelligenceIntelProfile', 
               'Remove-MgBetaSecurityThreatIntelligencePassiveDnsRecord', 
               'Remove-MgBetaSecurityThreatIntelligenceProfileIndicator', 
               'Remove-MgBetaSecurityThreatIntelligenceVulnerability', 
               'Remove-MgBetaSecurityThreatIntelligenceVulnerabilityComponent', 
               'Remove-MgBetaSecurityThreatSubmission', 
               'Remove-MgBetaSecurityThreatSubmissionEmailThreat', 
               'Remove-MgBetaSecurityThreatSubmissionEmailThreatSubmissionPolicy', 
               'Remove-MgBetaSecurityThreatSubmissionFileThreat', 
               'Remove-MgBetaSecurityThreatSubmissionUrlThreat', 
               'Remove-MgBetaSecurityTiIndicator', 
               'Remove-MgBetaSecurityTiIndicatorByExternalId', 
               'Remove-MgBetaSecurityTiIndicatorMultiple', 
               'Remove-MgBetaSecurityTrigger', 
               'Remove-MgBetaSecurityTriggerRetentionEvent', 
               'Remove-MgBetaSecurityTriggerType', 
               'Remove-MgBetaSecurityTriggerTypeRetentionEventType', 
               'Remove-MgBetaSecurityUserSecurityProfile', 
               'Reset-MgBetaSecurityCaseEdiscoveryCaseSettingToDefault', 
               'Set-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileContent', 
               'Set-MgBetaSecurityCaseEdiscoveryCaseReviewSetFileExtractedTextContent', 
               'Start-MgBetaSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Start-MgBetaSecurityHuntingQuery', 'Stop-MgBetaSecurityAction', 
               'Submit-MgBetaSecurityTiIndicator', 
               'Test-MgBetaSecurityInformationProtectionSensitivityLabelApplication', 
               'Test-MgBetaSecurityInformationProtectionSensitivityLabelClassificationResult', 
               'Test-MgBetaSecurityInformationProtectionSensitivityLabelRemoval', 
               'Update-MgBetaSecurityAction', 'Update-MgBetaSecurityAlert', 
               'Update-MgBetaSecurityAlertMultiple', 
               'Update-MgBetaSecurityAlertV2', 
               'Update-MgBetaSecurityAttackSimulationAutomation', 
               'Update-MgBetaSecurityAttackSimulationAutomationRun', 
               'Update-MgBetaSecurityAttackSimulationOperation', 
               'Update-MgBetaSecurityAttackSimulationPayload', 
               'Update-MgBetaSecurityCase', 
               'Update-MgBetaSecurityCaseEdiscoveryCase', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseCustodian', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseCustodianIndex', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseLegalHold', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseLegalHoldSiteSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseLegalHoldUserSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseNoncustodialDataSourceIndex', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseOperation', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseReviewSet', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseReviewSetFile', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseSearch', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseSetting', 
               'Update-MgBetaSecurityCaseEdiscoveryCaseTag', 
               'Update-MgBetaSecurityCloudAppSecurityProfile', 
               'Update-MgBetaSecurityDomainSecurityProfile', 
               'Update-MgBetaSecurityFileSecurityProfile', 
               'Update-MgBetaSecurityHostSecurityProfile', 
               'Update-MgBetaSecurityIncident', 
               'Update-MgBetaSecurityInformationProtection', 
               'Update-MgBetaSecurityInformationProtectionLabelPolicySetting', 
               'Update-MgBetaSecurityInformationProtectionSensitivityLabel', 
               'Update-MgBetaSecurityInformationProtectionSensitivityLabelParent', 
               'Update-MgBetaSecurityIPSecurityProfile', 
               'Update-MgBetaSecurityLabel', 
               'Update-MgBetaSecurityLabelRetentionLabel', 
               'Update-MgBetaSecurityLabelRetentionLabelDispositionReviewStage', 
               'Update-MgBetaSecurityProviderTenantSetting', 
               'Update-MgBetaSecuritySecureScore', 
               'Update-MgBetaSecuritySecureScoreControlProfile', 
               'Update-MgBetaSecuritySubjectRightsRequest', 
               'Update-MgBetaSecuritySubjectRightsRequestApproverMailboxSetting', 
               'Update-MgBetaSecuritySubjectRightsRequestCollaboratorMailboxSetting', 
               'Update-MgBetaSecuritySubjectRightsRequestNote', 
               'Update-MgBetaSecurityThreatIntelligence', 
               'Update-MgBetaSecurityThreatIntelligenceArticle', 
               'Update-MgBetaSecurityThreatIntelligenceArticleIndicator', 
               'Update-MgBetaSecurityThreatIntelligenceHost', 
               'Update-MgBetaSecurityThreatIntelligenceHostComponent', 
               'Update-MgBetaSecurityThreatIntelligenceHostCookie', 
               'Update-MgBetaSecurityThreatIntelligenceHostReputation', 
               'Update-MgBetaSecurityThreatIntelligenceHostTracker', 
               'Update-MgBetaSecurityThreatIntelligenceIntelProfile', 
               'Update-MgBetaSecurityThreatIntelligencePassiveDnsRecord', 
               'Update-MgBetaSecurityThreatIntelligenceProfileIndicator', 
               'Update-MgBetaSecurityThreatIntelligenceVulnerability', 
               'Update-MgBetaSecurityThreatIntelligenceVulnerabilityComponent', 
               'Update-MgBetaSecurityThreatSubmission', 
               'Update-MgBetaSecurityThreatSubmissionEmailThreat', 
               'Update-MgBetaSecurityThreatSubmissionEmailThreatSubmissionPolicy', 
               'Update-MgBetaSecurityThreatSubmissionFileThreat', 
               'Update-MgBetaSecurityThreatSubmissionUrlThreat', 
               'Update-MgBetaSecurityTiIndicator', 
               'Update-MgBetaSecurityTiIndicatorMultiple', 
               'Update-MgBetaSecurityTrigger', 
               'Update-MgBetaSecurityTriggerRetentionEvent', 
               'Update-MgBetaSecurityTriggerType', 
               'Update-MgBetaSecurityTriggerTypeRetentionEventType', 
               'Update-MgBetaSecurityUserSecurityProfile'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        Prerelease = 'preview10'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

