#
# Module manifest for module 'Microsoft.Graph.Beta.Identity.DirectoryManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/8/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.Identity.DirectoryManagement.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '798c4739-1e4f-4109-a97f-9828a78e7ca5'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.0.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 
               './bin/Microsoft.Graph.Beta.Identity.DirectoryManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 
               './Microsoft.Graph.Beta.Identity.DirectoryManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Complete-MgBetaDirectoryImpactedResource', 
               'Complete-MgBetaDirectoryRecommendation', 
               'Confirm-MgBetaAdministrativeUnitMemberGroup', 
               'Confirm-MgBetaAdministrativeUnitMemberObject', 
               'Confirm-MgBetaContactMemberGroup', 
               'Confirm-MgBetaContactMemberObject', 
               'Confirm-MgBetaContractMemberGroup', 
               'Confirm-MgBetaContractMemberObject', 
               'Confirm-MgBetaDeviceMemberGroup', 
               'Confirm-MgBetaDeviceMemberObject', 
               'Confirm-MgBetaDirectoryAdministrativeUnitMemberGroup', 
               'Confirm-MgBetaDirectoryAdministrativeUnitMemberObject', 
               'Confirm-MgBetaDirectoryDeletedItemMemberGroup', 
               'Confirm-MgBetaDirectoryDeletedItemMemberObject', 
               'Confirm-MgBetaDirectoryRoleMemberGroup', 
               'Confirm-MgBetaDirectoryRoleMemberObject', 
               'Confirm-MgBetaDirectoryRoleTemplateMemberGroup', 
               'Confirm-MgBetaDirectoryRoleTemplateMemberObject', 
               'Confirm-MgBetaDirectorySettingTemplateMemberGroup', 
               'Confirm-MgBetaDirectorySettingTemplateMemberObject', 
               'Confirm-MgBetaDomain', 'Confirm-MgBetaOrganizationMemberGroup', 
               'Confirm-MgBetaOrganizationMemberObject', 
               'Export-MgBetaDirectoryInboundSharedUserProfilePersonalData', 
               'Get-MgBetaAdministrativeUnit', 'Get-MgBetaAdministrativeUnitById', 
               'Get-MgBetaAdministrativeUnitCount', 
               'Get-MgBetaAdministrativeUnitDelta', 
               'Get-MgBetaAdministrativeUnitExtension', 
               'Get-MgBetaAdministrativeUnitExtensionCount', 
               'Get-MgBetaAdministrativeUnitListMemberCountAsApplication', 
               'Get-MgBetaAdministrativeUnitListMemberCountAsDevice', 
               'Get-MgBetaAdministrativeUnitListMemberCountAsGroup', 
               'Get-MgBetaAdministrativeUnitListMemberCountAsOrgContact', 
               'Get-MgBetaAdministrativeUnitListMemberCountAsServicePrincipal', 
               'Get-MgBetaAdministrativeUnitListMemberCountAsUser', 
               'Get-MgBetaAdministrativeUnitMember', 
               'Get-MgBetaAdministrativeUnitMemberAsApplication', 
               'Get-MgBetaAdministrativeUnitMemberAsDevice', 
               'Get-MgBetaAdministrativeUnitMemberAsGroup', 
               'Get-MgBetaAdministrativeUnitMemberAsOrgContact', 
               'Get-MgBetaAdministrativeUnitMemberAsServicePrincipal', 
               'Get-MgBetaAdministrativeUnitMemberAsUser', 
               'Get-MgBetaAdministrativeUnitMemberByRef', 
               'Get-MgBetaAdministrativeUnitMemberCount', 
               'Get-MgBetaAdministrativeUnitMemberGroup', 
               'Get-MgBetaAdministrativeUnitMemberObject', 
               'Get-MgBetaAdministrativeUnitScopedRoleMember', 
               'Get-MgBetaAdministrativeUnitScopedRoleMemberCount', 
               'Get-MgBetaAdministrativeUnitUserOwnedObject', 'Get-MgBetaContact', 
               'Get-MgBetaContactById', 'Get-MgBetaContactCount', 
               'Get-MgBetaContactDelta', 'Get-MgBetaContactDirectReport', 
               'Get-MgBetaContactDirectReportAsOrgContact', 
               'Get-MgBetaContactDirectReportAsUser', 
               'Get-MgBetaContactDirectReportCount', 
               'Get-MgBetaContactListDirectReportCountAsOrgContact', 
               'Get-MgBetaContactListDirectReportCountAsUser', 
               'Get-MgBetaContactListMemberOfCountAsAdministrativeUnit', 
               'Get-MgBetaContactListMemberOfCountAsGroup', 
               'Get-MgBetaContactListTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgBetaContactListTransitiveMemberOfCountAsGroup', 
               'Get-MgBetaContactManager', 'Get-MgBetaContactMemberGroup', 
               'Get-MgBetaContactMemberObject', 'Get-MgBetaContactMemberOf', 
               'Get-MgBetaContactMemberOfAsAdministrativeUnit', 
               'Get-MgBetaContactMemberOfAsGroup', 
               'Get-MgBetaContactMemberOfCount', 
               'Get-MgBetaContactTransitiveMemberOf', 
               'Get-MgBetaContactTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgBetaContactTransitiveMemberOfAsGroup', 
               'Get-MgBetaContactTransitiveMemberOfCount', 
               'Get-MgBetaContactTransitiveReport', 
               'Get-MgBetaContactTransitiveReportCount', 
               'Get-MgBetaContactUserOwnedObject', 'Get-MgBetaContract', 
               'Get-MgBetaContractById', 'Get-MgBetaContractCount', 
               'Get-MgBetaContractDelta', 'Get-MgBetaContractMemberGroup', 
               'Get-MgBetaContractMemberObject', 
               'Get-MgBetaContractUserOwnedObject', 'Get-MgBetaDevice', 
               'Get-MgBetaDeviceById', 'Get-MgBetaDeviceCommand', 
               'Get-MgBetaDeviceCommandCount', 
               'Get-MgBetaDeviceCommandResponsepayload', 'Get-MgBetaDeviceCount', 
               'Get-MgBetaDeviceDelta', 'Get-MgBetaDeviceExtension', 
               'Get-MgBetaDeviceExtensionCount', 
               'Get-MgBetaDeviceListMemberOfCountAsAdministrativeUnit', 
               'Get-MgBetaDeviceListMemberOfCountAsGroup', 
               'Get-MgBetaDeviceListRegisteredOwnerCountAsEndpoint', 
               'Get-MgBetaDeviceListRegisteredOwnerCountAsServicePrincipal', 
               'Get-MgBetaDeviceListRegisteredOwnerCountAsUser', 
               'Get-MgBetaDeviceListRegisteredUserCountAsEndpoint', 
               'Get-MgBetaDeviceListRegisteredUserCountAsServicePrincipal', 
               'Get-MgBetaDeviceListRegisteredUserCountAsUser', 
               'Get-MgBetaDeviceListTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgBetaDeviceListTransitiveMemberOfCountAsGroup', 
               'Get-MgBetaDeviceMemberGroup', 'Get-MgBetaDeviceMemberObject', 
               'Get-MgBetaDeviceMemberOf', 
               'Get-MgBetaDeviceMemberOfAsAdministrativeUnit', 
               'Get-MgBetaDeviceMemberOfAsGroup', 'Get-MgBetaDeviceMemberOfCount', 
               'Get-MgBetaDeviceRegisteredOwner', 
               'Get-MgBetaDeviceRegisteredOwnerAsEndpoint', 
               'Get-MgBetaDeviceRegisteredOwnerAsServicePrincipal', 
               'Get-MgBetaDeviceRegisteredOwnerAsUser', 
               'Get-MgBetaDeviceRegisteredOwnerByRef', 
               'Get-MgBetaDeviceRegisteredOwnerCount', 
               'Get-MgBetaDeviceRegisteredUser', 
               'Get-MgBetaDeviceRegisteredUserAsEndpoint', 
               'Get-MgBetaDeviceRegisteredUserAsServicePrincipal', 
               'Get-MgBetaDeviceRegisteredUserAsUser', 
               'Get-MgBetaDeviceRegisteredUserByRef', 
               'Get-MgBetaDeviceRegisteredUserCount', 
               'Get-MgBetaDeviceTransitiveMemberOf', 
               'Get-MgBetaDeviceTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgBetaDeviceTransitiveMemberOfAsGroup', 
               'Get-MgBetaDeviceTransitiveMemberOfCount', 
               'Get-MgBetaDeviceUsageRights', 'Get-MgBetaDeviceUsageRightsCount', 
               'Get-MgBetaDeviceUserOwnedObject', 'Get-MgBetaDirectory', 
               'Get-MgBetaDirectoryAdministrativeUnit', 
               'Get-MgBetaDirectoryAdministrativeUnitById', 
               'Get-MgBetaDirectoryAdministrativeUnitCount', 
               'Get-MgBetaDirectoryAdministrativeUnitDelta', 
               'Get-MgBetaDirectoryAdministrativeUnitExtension', 
               'Get-MgBetaDirectoryAdministrativeUnitExtensionCount', 
               'Get-MgBetaDirectoryAdministrativeUnitListMemberCountAsApplication', 
               'Get-MgBetaDirectoryAdministrativeUnitListMemberCountAsDevice', 
               'Get-MgBetaDirectoryAdministrativeUnitListMemberCountAsGroup', 
               'Get-MgBetaDirectoryAdministrativeUnitListMemberCountAsOrgContact', 
               'Get-MgBetaDirectoryAdministrativeUnitListMemberCountAsServicePrincipal', 
               'Get-MgBetaDirectoryAdministrativeUnitListMemberCountAsUser', 
               'Get-MgBetaDirectoryAdministrativeUnitMember', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberAsApplication', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberAsDevice', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberAsGroup', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberAsOrgContact', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberAsServicePrincipal', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberAsUser', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberByRef', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberCount', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberGroup', 
               'Get-MgBetaDirectoryAdministrativeUnitMemberObject', 
               'Get-MgBetaDirectoryAdministrativeUnitScopedRoleMember', 
               'Get-MgBetaDirectoryAdministrativeUnitScopedRoleMemberCount', 
               'Get-MgBetaDirectoryAdministrativeUnitUserOwnedObject', 
               'Get-MgBetaDirectoryAttributeSet', 
               'Get-MgBetaDirectoryAttributeSetCount', 
               'Get-MgBetaDirectoryCustomSecurityAttributeDefinition', 
               'Get-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Get-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValueCount', 
               'Get-MgBetaDirectoryCustomSecurityAttributeDefinitionCount', 
               'Get-MgBetaDirectoryDeletedItem', 
               'Get-MgBetaDirectoryDeletedItemAsApplication', 
               'Get-MgBetaDirectoryDeletedItemAsGroup', 
               'Get-MgBetaDirectoryDeletedItemAsUser', 
               'Get-MgBetaDirectoryDeletedItemById', 
               'Get-MgBetaDirectoryDeletedItemMemberGroup', 
               'Get-MgBetaDirectoryDeletedItemMemberObject', 
               'Get-MgBetaDirectoryDeletedItemUserOwnedObject', 
               'Get-MgBetaDirectoryFeatureRolloutPolicy', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyApplyTo', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyApplyToById', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyApplyToByRef', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyApplyToCount', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyApplyToDelta', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyApplyToUserOwnedObject', 
               'Get-MgBetaDirectoryFeatureRolloutPolicyCount', 
               'Get-MgBetaDirectoryFederationConfiguration', 
               'Get-MgBetaDirectoryFederationConfigurationCount', 
               'Get-MgBetaDirectoryImpactedResource', 
               'Get-MgBetaDirectoryImpactedResourceCount', 
               'Get-MgBetaDirectoryInboundSharedUserProfile', 
               'Get-MgBetaDirectoryInboundSharedUserProfileCount', 
               'Get-MgBetaDirectoryListDeletedItemCountAsApplication', 
               'Get-MgBetaDirectoryListDeletedItemCountAsGroup', 
               'Get-MgBetaDirectoryListDeletedItemCountAsUser', 
               'Get-MgBetaDirectoryOnPremiseSynchronization', 
               'Get-MgBetaDirectoryOnPremiseSynchronizationCount', 
               'Get-MgBetaDirectoryOutboundSharedUserProfile', 
               'Get-MgBetaDirectoryOutboundSharedUserProfileCount', 
               'Get-MgBetaDirectoryOutboundSharedUserProfileTenant', 
               'Get-MgBetaDirectoryOutboundSharedUserProfileTenantCount', 
               'Get-MgBetaDirectoryRecommendation', 
               'Get-MgBetaDirectoryRecommendationCount', 'Get-MgBetaDirectoryRole', 
               'Get-MgBetaDirectoryRoleById', 'Get-MgBetaDirectoryRoleCount', 
               'Get-MgBetaDirectoryRoleDelta', 
               'Get-MgBetaDirectoryRoleListMemberCountAsApplication', 
               'Get-MgBetaDirectoryRoleListMemberCountAsDevice', 
               'Get-MgBetaDirectoryRoleListMemberCountAsGroup', 
               'Get-MgBetaDirectoryRoleListMemberCountAsOrgContact', 
               'Get-MgBetaDirectoryRoleListMemberCountAsServicePrincipal', 
               'Get-MgBetaDirectoryRoleListMemberCountAsUser', 
               'Get-MgBetaDirectoryRoleMember', 
               'Get-MgBetaDirectoryRoleMemberAsApplication', 
               'Get-MgBetaDirectoryRoleMemberAsDevice', 
               'Get-MgBetaDirectoryRoleMemberAsGroup', 
               'Get-MgBetaDirectoryRoleMemberAsOrgContact', 
               'Get-MgBetaDirectoryRoleMemberAsServicePrincipal', 
               'Get-MgBetaDirectoryRoleMemberAsUser', 
               'Get-MgBetaDirectoryRoleMemberByRef', 
               'Get-MgBetaDirectoryRoleMemberCount', 
               'Get-MgBetaDirectoryRoleMemberGroup', 
               'Get-MgBetaDirectoryRoleMemberObject', 
               'Get-MgBetaDirectoryRoleScopedMember', 
               'Get-MgBetaDirectoryRoleScopedMemberCount', 
               'Get-MgBetaDirectoryRoleTemplate', 
               'Get-MgBetaDirectoryRoleTemplateById', 
               'Get-MgBetaDirectoryRoleTemplateCount', 
               'Get-MgBetaDirectoryRoleTemplateDelta', 
               'Get-MgBetaDirectoryRoleTemplateMemberGroup', 
               'Get-MgBetaDirectoryRoleTemplateMemberObject', 
               'Get-MgBetaDirectoryRoleTemplateUserOwnedObject', 
               'Get-MgBetaDirectoryRoleUserOwnedObject', 
               'Get-MgBetaDirectorySetting', 'Get-MgBetaDirectorySettingTemplate', 
               'Get-MgBetaDirectorySettingTemplateById', 
               'Get-MgBetaDirectorySettingTemplateCount', 
               'Get-MgBetaDirectorySettingTemplateDelta', 
               'Get-MgBetaDirectorySettingTemplateMemberGroup', 
               'Get-MgBetaDirectorySettingTemplateMemberObject', 
               'Get-MgBetaDirectorySettingTemplateUserOwnedObject', 
               'Get-MgBetaDirectorySharedEmailDomain', 
               'Get-MgBetaDirectorySharedEmailDomainCount', 'Get-MgBetaDomain', 
               'Get-MgBetaDomainCount', 'Get-MgBetaDomainFederationConfiguration', 
               'Get-MgBetaDomainFederationConfigurationCount', 
               'Get-MgBetaDomainNameReference', 
               'Get-MgBetaDomainNameReferenceCount', 
               'Get-MgBetaDomainServiceConfigurationRecord', 
               'Get-MgBetaDomainServiceConfigurationRecordCount', 
               'Get-MgBetaDomainSharedEmailDomainInvitation', 
               'Get-MgBetaDomainSharedEmailDomainInvitationCount', 
               'Get-MgBetaDomainVerificationDnsRecord', 
               'Get-MgBetaDomainVerificationDnsRecordCount', 
               'Get-MgBetaOrganization', 'Get-MgBetaOrganizationBranding', 
               'Get-MgBetaOrganizationBrandingBackgroundImage', 
               'Get-MgBetaOrganizationBrandingBannerLogo', 
               'Get-MgBetaOrganizationBrandingCustomCss', 
               'Get-MgBetaOrganizationBrandingFavicon', 
               'Get-MgBetaOrganizationBrandingHeaderLogo', 
               'Get-MgBetaOrganizationBrandingLocalization', 
               'Get-MgBetaOrganizationBrandingLocalizationBackgroundImage', 
               'Get-MgBetaOrganizationBrandingLocalizationBannerLogo', 
               'Get-MgBetaOrganizationBrandingLocalizationCount', 
               'Get-MgBetaOrganizationBrandingLocalizationCustomCss', 
               'Get-MgBetaOrganizationBrandingLocalizationFavicon', 
               'Get-MgBetaOrganizationBrandingLocalizationHeaderLogo', 
               'Get-MgBetaOrganizationBrandingLocalizationSquareLogo', 
               'Get-MgBetaOrganizationBrandingLocalizationSquareLogoDark', 
               'Get-MgBetaOrganizationBrandingSquareLogo', 
               'Get-MgBetaOrganizationBrandingSquareLogoDark', 
               'Get-MgBetaOrganizationById', 'Get-MgBetaOrganizationCount', 
               'Get-MgBetaOrganizationExtension', 
               'Get-MgBetaOrganizationExtensionCount', 
               'Get-MgBetaOrganizationMemberGroup', 
               'Get-MgBetaOrganizationMemberObject', 
               'Get-MgBetaOrganizationSetting', 
               'Get-MgBetaOrganizationSettingContactInsight', 
               'Get-MgBetaOrganizationSettingItemInsight', 
               'Get-MgBetaOrganizationSettingMicrosoftApplicationDataAccess', 
               'Get-MgBetaOrganizationSettingPersonInsight', 
               'Get-MgBetaOrganizationSettingProfileCardProperty', 
               'Get-MgBetaOrganizationSettingProfileCardPropertyCount', 
               'Get-MgBetaOrganizationSettingPronoun', 
               'Get-MgBetaOrganizationUserOwnedObject', 'Get-MgBetaSettingCount', 
               'Get-MgBetaSubscribedSku', 'Get-MgBetaUserScopedRoleMemberOf', 
               'Get-MgBetaUserScopedRoleMemberOfCount', 
               'Invoke-MgBetaAvailableDirectoryFederationConfigurationProviderType', 
               'Invoke-MgBetaDismissDirectoryImpactedResource', 
               'Invoke-MgBetaDismissDirectoryRecommendation', 
               'Invoke-MgBetaForceDomainDelete', 
               'Invoke-MgBetaPostponeDirectoryImpactedResource', 
               'Invoke-MgBetaPostponeDirectoryRecommendation', 
               'Invoke-MgBetaPromoteDomain', 
               'Invoke-MgBetaReactivateDirectoryImpactedResource', 
               'Invoke-MgBetaReactivateDirectoryRecommendation', 
               'Invoke-MgBetaRetryContactServiceProvisioning', 
               'New-MgBetaAdministrativeUnit', 
               'New-MgBetaAdministrativeUnitExtension', 
               'New-MgBetaAdministrativeUnitMemberByRef', 
               'New-MgBetaAdministrativeUnitScopedRoleMember', 'New-MgBetaContact', 
               'New-MgBetaContract', 'New-MgBetaDevice', 'New-MgBetaDeviceCommand', 
               'New-MgBetaDeviceExtension', 'New-MgBetaDeviceRegisteredOwnerByRef', 
               'New-MgBetaDeviceRegisteredUserByRef', 
               'New-MgBetaDeviceUsageRights', 
               'New-MgBetaDirectoryAdministrativeUnit', 
               'New-MgBetaDirectoryAdministrativeUnitExtension', 
               'New-MgBetaDirectoryAdministrativeUnitMemberByRef', 
               'New-MgBetaDirectoryAdministrativeUnitScopedRoleMember', 
               'New-MgBetaDirectoryAttributeSet', 
               'New-MgBetaDirectoryCustomSecurityAttributeDefinition', 
               'New-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'New-MgBetaDirectoryDeletedItem', 
               'New-MgBetaDirectoryFeatureRolloutPolicy', 
               'New-MgBetaDirectoryFeatureRolloutPolicyApplyTo', 
               'New-MgBetaDirectoryFeatureRolloutPolicyApplyToByRef', 
               'New-MgBetaDirectoryFederationConfiguration', 
               'New-MgBetaDirectoryImpactedResource', 
               'New-MgBetaDirectoryInboundSharedUserProfile', 
               'New-MgBetaDirectoryOnPremiseSynchronization', 
               'New-MgBetaDirectoryOutboundSharedUserProfile', 
               'New-MgBetaDirectoryOutboundSharedUserProfileTenant', 
               'New-MgBetaDirectoryRecommendation', 'New-MgBetaDirectoryRole', 
               'New-MgBetaDirectoryRoleMemberByRef', 
               'New-MgBetaDirectoryRoleScopedMember', 
               'New-MgBetaDirectoryRoleTemplate', 'New-MgBetaDirectorySetting', 
               'New-MgBetaDirectorySettingTemplate', 
               'New-MgBetaDirectorySharedEmailDomain', 'New-MgBetaDomain', 
               'New-MgBetaDomainFederationConfiguration', 
               'New-MgBetaDomainServiceConfigurationRecord', 
               'New-MgBetaDomainSharedEmailDomainInvitation', 
               'New-MgBetaDomainVerificationDnsRecord', 'New-MgBetaOrganization', 
               'New-MgBetaOrganizationBrandingLocalization', 
               'New-MgBetaOrganizationExtension', 
               'New-MgBetaOrganizationSettingProfileCardProperty', 
               'New-MgBetaSubscribedSku', 'New-MgBetaUserScopedRoleMemberOf', 
               'Remove-MgBetaAdministrativeUnit', 
               'Remove-MgBetaAdministrativeUnitExtension', 
               'Remove-MgBetaAdministrativeUnitMemberByRef', 
               'Remove-MgBetaAdministrativeUnitScopedRoleMember', 
               'Remove-MgBetaContact', 'Remove-MgBetaContract', 
               'Remove-MgBetaDevice', 'Remove-MgBetaDeviceCommand', 
               'Remove-MgBetaDeviceExtension', 
               'Remove-MgBetaDeviceRegisteredOwnerByRef', 
               'Remove-MgBetaDeviceRegisteredUserByRef', 
               'Remove-MgBetaDeviceUsageRights', 
               'Remove-MgBetaDirectoryAdministrativeUnit', 
               'Remove-MgBetaDirectoryAdministrativeUnitExtension', 
               'Remove-MgBetaDirectoryAdministrativeUnitMemberByRef', 
               'Remove-MgBetaDirectoryAdministrativeUnitScopedRoleMember', 
               'Remove-MgBetaDirectoryAttributeSet', 
               'Remove-MgBetaDirectoryCustomSecurityAttributeDefinition', 
               'Remove-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Remove-MgBetaDirectoryDeletedItem', 
               'Remove-MgBetaDirectoryFeatureRolloutPolicy', 
               'Remove-MgBetaDirectoryFeatureRolloutPolicyApplyToByRef', 
               'Remove-MgBetaDirectoryFederationConfiguration', 
               'Remove-MgBetaDirectoryImpactedResource', 
               'Remove-MgBetaDirectoryInboundSharedUserProfile', 
               'Remove-MgBetaDirectoryInboundSharedUserProfilePersonalData', 
               'Remove-MgBetaDirectoryOnPremiseSynchronization', 
               'Remove-MgBetaDirectoryOutboundSharedUserProfile', 
               'Remove-MgBetaDirectoryOutboundSharedUserProfileTenant', 
               'Remove-MgBetaDirectoryOutboundSharedUserProfileTenantPersonalData', 
               'Remove-MgBetaDirectoryRecommendation', 
               'Remove-MgBetaDirectoryRole', 
               'Remove-MgBetaDirectoryRoleMemberByRef', 
               'Remove-MgBetaDirectoryRoleScopedMember', 
               'Remove-MgBetaDirectoryRoleTemplate', 
               'Remove-MgBetaDirectorySetting', 
               'Remove-MgBetaDirectorySettingTemplate', 
               'Remove-MgBetaDirectorySharedEmailDomain', 'Remove-MgBetaDomain', 
               'Remove-MgBetaDomainFederationConfiguration', 
               'Remove-MgBetaDomainServiceConfigurationRecord', 
               'Remove-MgBetaDomainSharedEmailDomainInvitation', 
               'Remove-MgBetaDomainVerificationDnsRecord', 
               'Remove-MgBetaOrganization', 'Remove-MgBetaOrganizationBranding', 
               'Remove-MgBetaOrganizationBrandingLocalization', 
               'Remove-MgBetaOrganizationExtension', 
               'Remove-MgBetaOrganizationSetting', 
               'Remove-MgBetaOrganizationSettingContactInsight', 
               'Remove-MgBetaOrganizationSettingItemInsight', 
               'Remove-MgBetaOrganizationSettingMicrosoftApplicationDataAccess', 
               'Remove-MgBetaOrganizationSettingPersonInsight', 
               'Remove-MgBetaOrganizationSettingProfileCardProperty', 
               'Remove-MgBetaOrganizationSettingPronoun', 
               'Remove-MgBetaSubscribedSku', 'Remove-MgBetaUserScopedRoleMemberOf', 
               'Restore-MgBetaDirectoryDeletedItem', 
               'Set-MgBetaOrganizationBrandingBackgroundImage', 
               'Set-MgBetaOrganizationBrandingBannerLogo', 
               'Set-MgBetaOrganizationBrandingCustomCss', 
               'Set-MgBetaOrganizationBrandingFavicon', 
               'Set-MgBetaOrganizationBrandingHeaderLogo', 
               'Set-MgBetaOrganizationBrandingLocalizationBackgroundImage', 
               'Set-MgBetaOrganizationBrandingLocalizationBannerLogo', 
               'Set-MgBetaOrganizationBrandingLocalizationCustomCss', 
               'Set-MgBetaOrganizationBrandingLocalizationFavicon', 
               'Set-MgBetaOrganizationBrandingLocalizationHeaderLogo', 
               'Set-MgBetaOrganizationBrandingLocalizationSquareLogo', 
               'Set-MgBetaOrganizationBrandingLocalizationSquareLogoDark', 
               'Set-MgBetaOrganizationBrandingSquareLogo', 
               'Set-MgBetaOrganizationBrandingSquareLogoDark', 
               'Set-MgBetaOrganizationMobileDeviceManagementAuthority', 
               'Test-MgBetaAdministrativeUnitProperty', 
               'Test-MgBetaContactProperty', 'Test-MgBetaContractProperty', 
               'Test-MgBetaDeviceProperty', 
               'Test-MgBetaDirectoryAdministrativeUnitProperty', 
               'Test-MgBetaDirectoryDeletedItemProperty', 
               'Test-MgBetaDirectoryFeatureRolloutPolicyApplyToProperty', 
               'Test-MgBetaDirectoryRoleProperty', 
               'Test-MgBetaDirectoryRoleTemplateProperty', 
               'Test-MgBetaDirectorySettingTemplateProperty', 
               'Test-MgBetaOrganizationProperty', 
               'Update-MgBetaAdministrativeUnit', 
               'Update-MgBetaAdministrativeUnitExtension', 
               'Update-MgBetaAdministrativeUnitScopedRoleMember', 
               'Update-MgBetaContact', 'Update-MgBetaContract', 
               'Update-MgBetaDevice', 'Update-MgBetaDeviceCommand', 
               'Update-MgBetaDeviceExtension', 'Update-MgBetaDeviceUsageRights', 
               'Update-MgBetaDirectory', 
               'Update-MgBetaDirectoryAdministrativeUnit', 
               'Update-MgBetaDirectoryAdministrativeUnitExtension', 
               'Update-MgBetaDirectoryAdministrativeUnitScopedRoleMember', 
               'Update-MgBetaDirectoryAttributeSet', 
               'Update-MgBetaDirectoryCustomSecurityAttributeDefinition', 
               'Update-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Update-MgBetaDirectoryDeletedItem', 
               'Update-MgBetaDirectoryFeatureRolloutPolicy', 
               'Update-MgBetaDirectoryFederationConfiguration', 
               'Update-MgBetaDirectoryImpactedResource', 
               'Update-MgBetaDirectoryInboundSharedUserProfile', 
               'Update-MgBetaDirectoryOnPremiseSynchronization', 
               'Update-MgBetaDirectoryOutboundSharedUserProfile', 
               'Update-MgBetaDirectoryOutboundSharedUserProfileTenant', 
               'Update-MgBetaDirectoryRecommendation', 
               'Update-MgBetaDirectoryRole', 
               'Update-MgBetaDirectoryRoleScopedMember', 
               'Update-MgBetaDirectoryRoleTemplate', 
               'Update-MgBetaDirectorySetting', 
               'Update-MgBetaDirectorySettingTemplate', 
               'Update-MgBetaDirectorySharedEmailDomain', 'Update-MgBetaDomain', 
               'Update-MgBetaDomainFederationConfiguration', 
               'Update-MgBetaDomainServiceConfigurationRecord', 
               'Update-MgBetaDomainSharedEmailDomainInvitation', 
               'Update-MgBetaDomainVerificationDnsRecord', 
               'Update-MgBetaOrganization', 'Update-MgBetaOrganizationBranding', 
               'Update-MgBetaOrganizationBrandingLocalization', 
               'Update-MgBetaOrganizationExtension', 
               'Update-MgBetaOrganizationSetting', 
               'Update-MgBetaOrganizationSettingContactInsight', 
               'Update-MgBetaOrganizationSettingItemInsight', 
               'Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess', 
               'Update-MgBetaOrganizationSettingPersonInsight', 
               'Update-MgBetaOrganizationSettingProfileCardProperty', 
               'Update-MgBetaOrganizationSettingPronoun', 
               'Update-MgBetaSubscribedSku', 'Update-MgBetaUserScopedRoleMemberOf'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgDirectoryDeletedApplication', 'Get-MgDirectoryDeletedGroup', 
               'Get-MgDirectoryDeletedUser'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        Prerelease = 'preview10'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

