#
# Module manifest for module 'Microsoft.Graph.Devices.CorporateManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/8/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Devices.CorporateManagement.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '39dbb3bc-1a84-424a-9efe-683be70a1810'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.0.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Devices.CorporateManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Devices.CorporateManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MgDeviceAppManagement', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtection', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionAppCount', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionCount', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtection', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionAppCount', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionCount', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppManagementiOSManagedAppProtection', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionAppCount', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionCount', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppManagementListMobileAppCountAsManagedMobileLobApp', 
               'Get-MgDeviceAppManagementListMobileAppCountAsMobileLobApp', 
               'Get-MgDeviceAppManagementManagedAppPolicy', 
               'Get-MgDeviceAppManagementManagedAppPolicyCount', 
               'Get-MgDeviceAppManagementManagedAppRegistration', 
               'Get-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Get-MgDeviceAppManagementManagedAppRegistrationAppliedPolicyCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Get-MgDeviceAppManagementManagedAppRegistrationIntendedPolicyCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'Get-MgDeviceAppManagementManagedAppRegistrationOperationCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationUserIdWithFlaggedAppRegistration', 
               'Get-MgDeviceAppManagementManagedAppStatus', 
               'Get-MgDeviceAppManagementManagedAppStatusCount', 
               'Get-MgDeviceAppManagementManagedEBook', 
               'Get-MgDeviceAppManagementManagedEBookAssignment', 
               'Get-MgDeviceAppManagementManagedEBookAssignmentCount', 
               'Get-MgDeviceAppManagementManagedEBookCount', 
               'Get-MgDeviceAppManagementManagedEBookDeviceState', 
               'Get-MgDeviceAppManagementManagedEBookDeviceStateCount', 
               'Get-MgDeviceAppManagementManagedEBookInstallSummary', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummaryCount', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceStateCount', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyCount', 
               'Get-MgDeviceAppManagementMobileApp', 
               'Get-MgDeviceAppManagementMobileAppAsManagedMobileLobApp', 
               'Get-MgDeviceAppManagementMobileAppAsMobileLobApp', 
               'Get-MgDeviceAppManagementMobileAppAssignment', 
               'Get-MgDeviceAppManagementMobileAppAssignmentCount', 
               'Get-MgDeviceAppManagementMobileAppCategory', 
               'Get-MgDeviceAppManagementMobileAppCategoryCount', 
               'Get-MgDeviceAppManagementMobileAppConfiguration', 
               'Get-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'Get-MgDeviceAppManagementMobileAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Get-MgDeviceAppManagementMobileAppConfigurationDeviceStatusCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Get-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Get-MgDeviceAppManagementMobileAppConfigurationUserStatusCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Get-MgDeviceAppManagementMobileAppCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationAppCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Get-MgDeviceAppManagementVppToken', 
               'Get-MgDeviceAppManagementVppTokenCount', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyCount', 
               'Get-MgUserDeviceManagementTroubleshootingEvent', 
               'Get-MgUserDeviceManagementTroubleshootingEventCount', 
               'Get-MgUserManagedAppRegistration', 
               'Get-MgUserManagedAppRegistrationCount', 'Get-MgUserManagedDevice', 
               'Get-MgUserManagedDeviceCategory', 
               'Get-MgUserManagedDeviceCompliancePolicyState', 
               'Get-MgUserManagedDeviceCompliancePolicyStateCount', 
               'Get-MgUserManagedDeviceConfigurationState', 
               'Get-MgUserManagedDeviceConfigurationStateCount', 
               'Get-MgUserManagedDeviceCount', 'Get-MgUserManagedDeviceUser', 
               'Invoke-MgTargetDeviceAppManagementManagedAppPolicyApp', 
               'Invoke-MgTargetDeviceAppManagementManagedAppRegistrationAppliedPolicyApp', 
               'Invoke-MgTargetDeviceAppManagementManagedAppRegistrationIntendedPolicyApp', 
               'Invoke-MgTargetDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'New-MgDeviceAppManagementAndroidManagedAppProtection', 
               'New-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'New-MgDeviceAppManagementDefaultManagedAppProtection', 
               'New-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'New-MgDeviceAppManagementiOSManagedAppProtection', 
               'New-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'New-MgDeviceAppManagementManagedAppPolicy', 
               'New-MgDeviceAppManagementManagedAppRegistration', 
               'New-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'New-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'New-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'New-MgDeviceAppManagementManagedAppStatus', 
               'New-MgDeviceAppManagementManagedEBook', 
               'New-MgDeviceAppManagementManagedEBookAssignment', 
               'New-MgDeviceAppManagementManagedEBookDeviceState', 
               'New-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'New-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'New-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'New-MgDeviceAppManagementMobileApp', 
               'New-MgDeviceAppManagementMobileAppAssignment', 
               'New-MgDeviceAppManagementMobileAppCategory', 
               'New-MgDeviceAppManagementMobileAppConfiguration', 
               'New-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'New-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'New-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'New-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'New-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'New-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'New-MgDeviceAppManagementVppToken', 
               'New-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'New-MgUserDeviceManagementTroubleshootingEvent', 
               'New-MgUserManagedDevice', 
               'New-MgUserManagedDeviceCompliancePolicyState', 
               'New-MgUserManagedDeviceConfigurationState', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtection', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppManagementDefaultManagedAppProtection', 
               'Remove-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Remove-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtection', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppManagementManagedAppPolicy', 
               'Remove-MgDeviceAppManagementManagedAppRegistration', 
               'Remove-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Remove-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Remove-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'Remove-MgDeviceAppManagementManagedAppStatus', 
               'Remove-MgDeviceAppManagementManagedEBook', 
               'Remove-MgDeviceAppManagementManagedEBookAssignment', 
               'Remove-MgDeviceAppManagementManagedEBookDeviceState', 
               'Remove-MgDeviceAppManagementManagedEBookInstallSummary', 
               'Remove-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'Remove-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Remove-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Remove-MgDeviceAppManagementMobileApp', 
               'Remove-MgDeviceAppManagementMobileAppAssignment', 
               'Remove-MgDeviceAppManagementMobileAppCategory', 
               'Remove-MgDeviceAppManagementMobileAppConfiguration', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Remove-MgDeviceAppManagementVppToken', 
               'Remove-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Remove-MgUserDeviceManagementTroubleshootingEvent', 
               'Remove-MgUserManagedDevice', 'Remove-MgUserManagedDeviceCategory', 
               'Remove-MgUserManagedDeviceCompliancePolicyState', 
               'Remove-MgUserManagedDeviceConfigurationState', 
               'Set-MgDeviceAppManagementManagedEBook', 
               'Set-MgDeviceAppManagementMobileApp', 
               'Set-MgDeviceAppManagementMobileAppConfiguration', 
               'Set-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Sync-MgDeviceAppManagementMicrosoftStoreForBusinessApp', 
               'Sync-MgDeviceAppManagementVppTokenLicense', 
               'Update-MgDeviceAppManagement', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtection', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppManagementDefaultManagedAppProtection', 
               'Update-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Update-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppManagementiOSManagedAppProtection', 
               'Update-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'Update-MgDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppManagementManagedAppPolicy', 
               'Update-MgDeviceAppManagementManagedAppRegistration', 
               'Update-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Update-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Update-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'Update-MgDeviceAppManagementManagedAppStatus', 
               'Update-MgDeviceAppManagementManagedEBook', 
               'Update-MgDeviceAppManagementManagedEBookAssignment', 
               'Update-MgDeviceAppManagementManagedEBookDeviceState', 
               'Update-MgDeviceAppManagementManagedEBookInstallSummary', 
               'Update-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'Update-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Update-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Update-MgDeviceAppManagementMobileApp', 
               'Update-MgDeviceAppManagementMobileAppAssignment', 
               'Update-MgDeviceAppManagementMobileAppCategory', 
               'Update-MgDeviceAppManagementMobileAppConfiguration', 
               'Update-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'Update-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Update-MgDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Update-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Update-MgDeviceAppManagementVppToken', 
               'Update-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Update-MgUserDeviceManagementTroubleshootingEvent', 
               'Update-MgUserManagedDevice', 'Update-MgUserManagedDeviceCategory', 
               'Update-MgUserManagedDeviceCompliancePolicyState', 
               'Update-MgUserManagedDeviceConfigurationState'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgDeviceAppMgt', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtection', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionAppCount', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionCount', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtection', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionAppCount', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionCount', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppMgtIoManagedAppProtection', 
               'Get-MgDeviceAppMgtIoManagedAppProtectionApp', 
               'Get-MgDeviceAppMgtIoManagedAppProtectionAppCount', 
               'Get-MgDeviceAppMgtIoManagedAppProtectionCount', 
               'Get-MgDeviceAppMgtIoManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppMgtListMobileAppCountAsManagedMobileLobApp', 
               'Get-MgDeviceAppMgtListMobileAppCountAsMobileLobApp', 
               'Get-MgDeviceAppMgtManagedAppPolicy', 
               'Get-MgDeviceAppMgtManagedAppPolicyCount', 
               'Get-MgDeviceAppMgtManagedAppRegistration', 
               'Get-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Get-MgDeviceAppMgtManagedAppRegistrationAppliedPolicyCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Get-MgDeviceAppMgtManagedAppRegistrationIntendedPolicyCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'Get-MgDeviceAppMgtManagedAppRegistrationOperationCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationUserIdGraphWPreFlaggedAppRegistration', 
               'Get-MgDeviceAppMgtManagedAppStatus', 
               'Get-MgDeviceAppMgtManagedAppStatusCount', 
               'Get-MgDeviceAppMgtManagedEBook', 
               'Get-MgDeviceAppMgtManagedEBookAssignment', 
               'Get-MgDeviceAppMgtManagedEBookAssignmentCount', 
               'Get-MgDeviceAppMgtManagedEBookCount', 
               'Get-MgDeviceAppMgtManagedEBookDeviceState', 
               'Get-MgDeviceAppMgtManagedEBookDeviceStateCount', 
               'Get-MgDeviceAppMgtManagedEBookInstallSummary', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummaryCount', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceStateCount', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyCount', 
               'Get-MgDeviceAppMgtMobileApp', 
               'Get-MgDeviceAppMgtMobileAppAsManagedMobileLobApp', 
               'Get-MgDeviceAppMgtMobileAppAsMobileLobApp', 
               'Get-MgDeviceAppMgtMobileAppAssignment', 
               'Get-MgDeviceAppMgtMobileAppAssignmentCount', 
               'Get-MgDeviceAppMgtMobileAppCategory', 
               'Get-MgDeviceAppMgtMobileAppCategoryCount', 
               'Get-MgDeviceAppMgtMobileAppConfiguration', 
               'Get-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'Get-MgDeviceAppMgtMobileAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Get-MgDeviceAppMgtMobileAppConfigurationDeviceStatusCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Get-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Get-MgDeviceAppMgtMobileAppConfigurationUserStatusCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Get-MgDeviceAppMgtMobileAppCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationAppCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Get-MgDeviceAppMgtVppToken', 'Get-MgDeviceAppMgtVppTokenCount', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyCount', 
               'New-MgDeviceAppMgtAndroidManagedAppProtection', 
               'New-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'New-MgDeviceAppMgtDefaultManagedAppProtection', 
               'New-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'New-MgDeviceAppMgtIoManagedAppProtection', 
               'New-MgDeviceAppMgtIoManagedAppProtectionApp', 
               'New-MgDeviceAppMgtManagedAppPolicy', 
               'New-MgDeviceAppMgtManagedAppRegistration', 
               'New-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'New-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'New-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'New-MgDeviceAppMgtManagedAppStatus', 
               'New-MgDeviceAppMgtManagedEBook', 
               'New-MgDeviceAppMgtManagedEBookAssignment', 
               'New-MgDeviceAppMgtManagedEBookDeviceState', 
               'New-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'New-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'New-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'New-MgDeviceAppMgtMobileApp', 
               'New-MgDeviceAppMgtMobileAppAssignment', 
               'New-MgDeviceAppMgtMobileAppCategory', 
               'New-MgDeviceAppMgtMobileAppConfiguration', 
               'New-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'New-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'New-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'New-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'New-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'New-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'New-MgDeviceAppMgtVppToken', 
               'New-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtection', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppMgtDefaultManagedAppProtection', 
               'Remove-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Remove-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppMgtIoManagedAppProtection', 
               'Remove-MgDeviceAppMgtIoManagedAppProtectionApp', 
               'Remove-MgDeviceAppMgtIoManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppMgtManagedAppPolicy', 
               'Remove-MgDeviceAppMgtManagedAppRegistration', 
               'Remove-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Remove-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Remove-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'Remove-MgDeviceAppMgtManagedAppStatus', 
               'Remove-MgDeviceAppMgtManagedEBook', 
               'Remove-MgDeviceAppMgtManagedEBookAssignment', 
               'Remove-MgDeviceAppMgtManagedEBookDeviceState', 
               'Remove-MgDeviceAppMgtManagedEBookInstallSummary', 
               'Remove-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'Remove-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Remove-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Remove-MgDeviceAppMgtMobileApp', 
               'Remove-MgDeviceAppMgtMobileAppAssignment', 
               'Remove-MgDeviceAppMgtMobileAppCategory', 
               'Remove-MgDeviceAppMgtMobileAppConfiguration', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Remove-MgDeviceAppMgtVppToken', 
               'Remove-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'Set-MgDeviceAppMgtManagedEBook', 'Set-MgDeviceAppMgtMobileApp', 
               'Set-MgDeviceAppMgtMobileAppConfiguration', 
               'Set-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Sync-MgDeviceAppMgtMicrosoftStoreGraphFPreBusinessApp', 
               'Sync-MgDeviceAppMgtVppTokenLicense', 'Update-MgDeviceAppMgt', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtection', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppMgtDefaultManagedAppProtection', 
               'Update-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Update-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppMgtIoManagedAppProtection', 
               'Update-MgDeviceAppMgtIoManagedAppProtectionApp', 
               'Update-MgDeviceAppMgtIoManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppMgtManagedAppPolicy', 
               'Update-MgDeviceAppMgtManagedAppRegistration', 
               'Update-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Update-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Update-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'Update-MgDeviceAppMgtManagedAppStatus', 
               'Update-MgDeviceAppMgtManagedEBook', 
               'Update-MgDeviceAppMgtManagedEBookAssignment', 
               'Update-MgDeviceAppMgtManagedEBookDeviceState', 
               'Update-MgDeviceAppMgtManagedEBookInstallSummary', 
               'Update-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'Update-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Update-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Update-MgDeviceAppMgtMobileApp', 
               'Update-MgDeviceAppMgtMobileAppAssignment', 
               'Update-MgDeviceAppMgtMobileAppCategory', 
               'Update-MgDeviceAppMgtMobileAppConfiguration', 
               'Update-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'Update-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Update-MgDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Update-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Update-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Update-MgDeviceAppMgtVppToken', 
               'Update-MgDeviceAppMgtWindowInformationProtectionPolicy'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        Prerelease = 'preview10'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

